// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/careers-homepage/CareersFirst.tsx": () => import("../components/mockups/careers-homepage/CareersFirst.tsx"),
  "./components/mockups/careers-homepage/Current.tsx": () => import("../components/mockups/careers-homepage/Current.tsx")
};
